export const ActionType = {
  /* Login and Registration */
  REGISTER__START: "REGISTER__START",
  REGISTER__SUCCSESS: " REGISTER__SUCCSESS",
  REGISTER__ERROR: "REGISTER__ERROR",
  LOGIN__START: "LOGIN__START",
  LOGIN__SUCCSESS: " LOGIN__SUCCSESS",
  LOGIN__ERROR: "LOGIN__ERROR",
  LOGOUT__START: "LOGOUT__START",
  LOGOUT__SUCCSESS: "LOGOUT__SUCCSESS",
  LOGOUT__ERROR: "LOGOUT__ERROR",
  /* Product */
  GET__PRODUCT__BY__BRAND: "GET__PRODUCT__BY__BRAND",
  ADD__CART: "ADD__CART",
  REMOVE__ITEM__FROM__CART: "REMOVE__ITEM__FROM__CART",
  GET__TOTAL__PRICE: "GET__TOTAL__PRICE",
  GET__QTY__AND__UPDATA__TOTAL: "GET__QTY__AND__UPDATA__TOTAL",
  ADD__LIST: "ADD__LIST",
  REMOVE__ITEM__FROM__LIST: "REMOVE__ITEM__FROM__LIST",
};
